[package]
name = "basecamp_es_final"
version = "0.1.0"
description = "Workshop to learn the basics of testing a contract."
homepage = ""

[dependencies]
starknet = ">=1.0.0"

[scripts]
test = "cairo-test --starknet ."
test_single= "cairo-test --starknet . -f"

[[target.starknet-contract]]
